from google import genai

from backend.config import settings


class GeminiGenerationError(Exception):
    """Raised when Gemini document generation fails."""


class GeminiGenerator:
    """
    Handles communication with the Google Gemini API.

    The API key is loaded from the local .env file through
    the application's Settings object.
    """

    def __init__(self) -> None:
        if not settings.gemini_api_key:
            raise GeminiGenerationError(
                "GEMINI_API_KEY is not configured. "
                "Add your Gemini API key to the local .env file."
            )

        self.client = genai.Client(
            api_key=settings.gemini_api_key
        )

        self.model = settings.gemini_model

    def generate_legal_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: str,
    ) -> str:
        """
        Generate a structured legal document using Gemini.
        """

        prompt = f"""
You are LegalEase, an AI-powered legal document drafting assistant.

Your task is to generate a professional draft legal document based
ONLY on the information supplied by the user.

IMPORTANT:
- This is an AI-generated draft and is not a substitute for advice
  from a qualified lawyer.
- Do not invent names, dates, amounts, addresses, obligations,
  jurisdictions, laws, clauses, or facts that were not provided.
- If important information is missing, use a clear placeholder such
  as [MISSING INFORMATION] instead of inventing information.
- Do not claim that the document guarantees a particular legal result.
- Use clear, professional legal language.
- Keep the document internally consistent.
- Do not include markdown code fences.
- Do not discuss your reasoning.
- Return only the actual document content.

DOCUMENT TYPE:
{document_type}

PARTIES:
{parties}

TERMS AND CONDITIONS:
{terms}

EFFECTIVE DATE:
{effective_date}

Create the legal document using this general structure where appropriate:

1. Document title
2. Introduction / purpose
3. Parties
4. Effective date
5. Definitions, if needed
6. Main terms and obligations
7. Payment / consideration, if applicable
8. Confidentiality, if applicable
9. Intellectual property, if applicable
10. Term and termination, if applicable
11. Representations and responsibilities, if applicable
12. Dispute resolution, if applicable
13. Governing law, ONLY if supplied by the user
14. Miscellaneous provisions
15. Signature section

For the signature section, use placeholders where information
has not been provided.

End the document with:

AI DRAFT NOTICE:
This document was generated by LegalEase using generative AI.
It should be reviewed by a qualified legal professional before
being signed or relied upon.
"""

        try:
            interaction = self.client.interactions.create(
                model=self.model,
                input=prompt,
                store=False,
            )

            generated_text = getattr(
                interaction,
                "output_text",
                None,
            )

            if not generated_text or not generated_text.strip():
                raise GeminiGenerationError(
                    "Gemini returned an empty response."
                )

            return generated_text.strip()

        except GeminiGenerationError:
            raise

        except Exception as exc:
            raise GeminiGenerationError(
                f"Gemini generation failed: {exc}"
            ) from exc


def generate_legal_document(
    document_type: str,
    parties: str,
    terms: str,
    effective_date: str,
) -> str:
    """
    Convenience function used by the FastAPI backend.
    """

    generator = GeminiGenerator()

    return generator.generate_legal_document(
        document_type=document_type,
        parties=parties,
        terms=terms,
        effective_date=effective_date,
    )