from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, Mm

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


def create_txt(document_text: str) -> bytes:
    """
    Create a plain-text document.
    """
    return document_text.encode("utf-8")


def create_docx(document_text: str) -> bytes:
    """
    Create a formatted DOCX document.
    """

    document = Document()

    section = document.sections[0]

    section.top_margin = Mm(20)
    section.bottom_margin = Mm(20)
    section.left_margin = Mm(20)
    section.right_margin = Mm(20)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run("LEGALEASE")
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(18)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = subtitle.add_run("AI-Powered Legal Document")
    run.font.name = "Times New Roman"
    run.font.size = Pt(11)

    document.add_paragraph()

    for line in document_text.splitlines():
        paragraph = document.add_paragraph()

        run = paragraph.add_run(line)
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)

    notice = document.add_paragraph()
    notice.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = notice.add_run(
        "AI-generated draft. Review by a qualified legal "
        "professional before signing or relying upon this document."
    )
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(10)

    output = BytesIO()
    document.save(output)

    return output.getvalue()


def create_pdf(document_text: str) -> bytes:
    """
    Create a formatted PDF document.
    """

    output = BytesIO()

    document = SimpleDocTemplate(
        output,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "LegalEaseTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "LegalEaseSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "LegalEaseBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        spaceAfter=6,
    )

    notice_style = ParagraphStyle(
        "LegalEaseNotice",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        alignment=TA_CENTER,
        spaceBefore=12,
    )

    story = []

    story.append(
        Paragraph(
            "LEGALEASE",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Legal Document",
            subtitle_style,
        )
    )

    story.append(Spacer(1, 8))

    for line in document_text.splitlines():
        if line.strip():
            safe_line = (
                line.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )

            story.append(
                Paragraph(
                    safe_line,
                    body_style,
                )
            )

    story.append(
        Paragraph(
            "AI DRAFT NOTICE: This document was generated by "
            "LegalEase using generative AI. It should be reviewed "
            "by a qualified legal professional before being signed "
            "or relied upon.",
            notice_style,
        )
    )

    document.build(
        story,
        onFirstPage=_add_pdf_header_footer,
        onLaterPages=_add_pdf_header_footer,
    )

    return output.getvalue()


def _add_pdf_header_footer(canvas, doc):
    """
    Add LegalEase header and footer to PDF pages.
    """

    canvas.saveState()

    width, height = A4

    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(
        20 * mm,
        height - 15 * mm,
        "LegalEase",
    )

    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        width - 20 * mm,
        10 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()